# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlsyGln4ST-TmbiYNkRsnOrJCb6MZw9n
"""

import pandas as pd
import numpy as np

cars=pd.read_csv("/content/Automobile_data.csv")

cars.shape

cars.head()

cars["price"].describe

cars["price"].isna().any()

cars.replace("?",np.nan,inplace=True)

cars["price"].isna().sum()

cars.head()

cars

cars.describe()

cars.dropna(inplace=True)

cars.replace("two",2,inplace=True)

cars.replace("four",4,inplace=True)

cars.head()

cars["num-of-doors"]=cars["num-of-doors"].astype(int)

cars.head()

